import { ConfigurePdfResponse } from '@/types/api';

export const mockConfigureResponse: ConfigurePdfResponse = {
  name: '',
  header: {
    '0': {
      fieldname: 'Bestellnr',
      label: '',
      logic: '0',
      prompt: '',
      selected: false,
      first: '10013',
    },
    '1': {
      fieldname: 'Bedat',
      label: '',
      logic: '0',
      prompt: '',
      selected: false,
      first: '23.05.2020',
    },
    '2': {
      fieldname: 'Tel',
      label: '',
      logic: '0',
      prompt: '',
      selected: false,
      first: '+49 123 456789',
    },
    '3': {
      fieldname: 'Info',
      label: '',
      logic: '0',
      prompt: '',
      selected: false,
      first: 'Delivery expected by 30.05.2020',
    },
    '4': {
      fieldname: 'Lieferant',
      label: '',
      logic: '0',
      prompt: '',
      selected: false,
      first: 'ABC Suppliers Ltd.',
    },
    '5': {
      fieldname: 'Lieferadresse',
      label: '',
      logic: '0',
      prompt: '',
      selected: false,
      first: 'Main Warehouse, 123 Business St.',
    },
    '6': {
      fieldname: 'Zahlungsbedingungen',
      label: '',
      logic: '0',
      prompt: '',
      selected: false,
      first: 'Net 30',
    },
  },
  item: {
    '0': {
      fieldname: 'Artikelnummer',
      label: '',
      logic: '0',
      prompt: '',
      selected: false,
      first: '10',
    },
    '1': {
      fieldname: 'Beschreibung',
      label: '',
      logic: '0',
      prompt: '',
      selected: false,
      first: 'Jol er balti',
    },
    '2': {
      fieldname: 'Menge',
      label: '',
      logic: '0',
      prompt: '',
      selected: false,
      first: '100',
    },
    '3': {
      fieldname: 'Preis',
      label: '',
      logic: '0',
      prompt: '',
      selected: false,
      first: '50',
    },
    '4': {
      fieldname: 'Einheit',
      label: '',
      logic: '0',
      prompt: '',
      selected: false,
      first: 'EA',
    },
    '5': {
      fieldname: 'Gesamt',
      label: '',
      logic: '0',
      prompt: '',
      selected: false,
      first: '5000',
    },
  },
};
